"""Binary STL writing helpers."""

from __future__ import annotations

import struct
from dataclasses import dataclass
from pathlib import Path

HEADER_TEXT = "Generated by GitHub Contributions Skyline Generator"
TRIANGLE_SIZE_BYTES = 50


@dataclass(frozen=True)
class Point3D:
    x: float
    y: float
    z: float


@dataclass(frozen=True)
class Triangle:
    normal: Point3D
    v1: Point3D
    v2: Point3D
    v3: Point3D


def _build_header() -> bytes:
    header = bytearray(80)
    encoded = HEADER_TEXT.encode("utf-8")
    header[: min(len(encoded), 80)] = encoded[:80]
    return bytes(header)


def _pack_triangle(tri: Triangle) -> bytes:
    return struct.pack(
        "<12fH",
        tri.normal.x,
        tri.normal.y,
        tri.normal.z,
        tri.v1.x,
        tri.v1.y,
        tri.v1.z,
        tri.v2.x,
        tri.v2.y,
        tri.v2.z,
        tri.v3.x,
        tri.v3.y,
        tri.v3.z,
        0,
    )


def write_stl_binary(path: str | Path, triangles: list[Triangle]) -> None:
    """Write triangles to binary STL file with Go-compatible header/count layout."""
    out_path = Path(path)
    if not str(out_path):
        raise ValueError("STL filename cannot be empty")

    with out_path.open("wb") as f:
        f.write(_build_header())
        f.write(struct.pack("<I", len(triangles)))
        for tri in triangles:
            f.write(_pack_triangle(tri))
